### PR TITLE
fix(cli) compute sizeU & height on modification

### LINKED ISSUE #487: Link sizeU and height attributs at device update
When updating sizeU or height of a device, it should also be update the other attribut.

### PR DESCRIPTION
**Pull request by Cedrok**
## Description

On a device update, if sizeU or height is modified, the CLI updates the other attribut.

Fixes #487 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Local test

### CODE REVIEW

File: CLI/controllers/update.go [hunk 1]
```diff
@@ -16,6 +16,41 @@ func (controller Controller) UpdateObj(pathStr string, data map[string]any, with
 		category = obj["category"].(string)
 	}
 
+	newAttrs, ok := data["attributes"].(map[string]any)
+	if ok {
+		if category == models.EntityToString(models.DEVICE) {
```
Comment (helderbetiol) [inline CLI/controllers/update.go:21]: Maybe a separate function and in models

File: CLI/controllers/update.go [hunk 2]
```diff
@@ -16,6 +16,41 @@ func (controller Controller) UpdateObj(pathStr string, data map[string]any, with
...
+					sizeU /= 100
+				case "mm":
+					sizeU /= 1000
+				}
+				newAttrs["sizeU"] = sizeU
+			}
+		}
+	}
+
 	url, err := controller.ObjectUrl(pathStr, 0)
```
Comment (helderbetiol) [inline CLI/controllers/update.go:54]: Should the API check if height and sizeU are coherent and refuse the request if not? In case flutter does not do the same as the CLI, for example.

File: CLI/controllers/update_test.go [hunk 3]
```diff
@@ -1,225 +1,204 @@
...
+			"sizeU": 1,
+		},
+	}
+	mockDataUpdate := map[string]any{
+		"attributes": map[string]any{
+			"sizeU":  float64(1),
+			"height": 44.45,
+		},
 	}
 	dataUpdated := map[string]any{
```
Comment (helderbetiol) [inline CLI/controllers/update_test.go:33]: Shouldn't this be the same as "device" but only with the PATCH values modified ?

File: CLI/controllers/update_test.go [hunk 4]
```diff
@@ -1,225 +1,204 @@
...
-	"cli/controllers"
 	"cli/models"
 	test_utils "cli/test"
-	"strings"
 	"testing"
 
 	"github.com/stretchr/testify/assert"
 )
 
-func TestUpdateTagColor(t *testing.T) {
```
Comment (helderbetiol) [inline CLI/controllers/update_test.go:13]: What happened to the original tests? Like TestUpdateTagColor.

File: CLI/models/attributes.go [hunk 5]
```diff
@@ -191,3 +193,31 @@ func expandStrToVector(slot string) ([]string, error) {
 		}
 	}
 }
+
+// Check the format of a sizeU attribute and return it as a float64 is possible
+func CheckSizeUFormat(value any) (float64, error) {
```
Comment (helderbetiol) [inline CLI/models/attributes.go:198]: Utils has a IsNumeric function, could simplify these two here

File: CLI/controllers/update_test.go (hunk 4 above)
Comment (Cedrok) [reply CLI/controllers/update_test.go:13]: They were deleted with outdated interact tests... They're back in [97e859e](https://github.com/ditrit/OGrEE-Core/pull/493/commits/97e859e8c9a36429e4c75a5cc027eb9cee162ad7)

File: CLI/models/attributes.go (hunk 5 above)
Comment (Cedrok) [reply CLI/models/attributes.go:198]: I'll use utils.GetFloat() instead : it does the same work as my functions..

File: CLI/controllers/update_test.go (hunk 3 above)
Comment (Cedrok) [reply CLI/controllers/update_test.go:91]: I didn't think we could reuse the same map, but it works!

File: CLI/controllers/update.go (hunk 2 above)
Comment (Cedrok) [reply CLI/controllers/update.go:23]: Done in [a2d5002](https://github.com/ditrit/OGrEE-Core/pull/493/commits/a2d500268327f56e85a142eabe8757e74f0ceaca)
