### PR TITLE
fix(cli, api): delete wildcard returns matches

### LINKED ISSUE #204: CLI should print the names of the deleted objects when using wildcard

### LINKED ISSUE #205: API returning status 200 instead of 204 when DELETE with wildcard has no match

### PR DESCRIPTION
**Pull request by GeremWD**
## Description

Fixes #204  
CLI prints "Nothing got deleted" in case there is no match.

## Type of change

- [ x ] New feature (non-breaking change which adds functionality)

### CODE REVIEW

File: API/controllers/entityController.go [hunk 1]
```diff
@@ -454,8 +454,7 @@ func HandleGenericObjectWildcard(w http.ResponseWriter, r *http.Request) {
 				u.RespondWithError(w, modelErr)
 			}
 		}
-		w.WriteHeader(http.StatusNoContent)
-		u.Respond(w, u.Message("successfully deleted"))
+		u.Respond(w, u.RespDataWrapper("successfully deleted objects", matchingObjects))
```
Comment (helderbetiol) [inline API/controllers/entityController.go:457]: This endpoint no longer exists with the refacto, so I copied this response to the delete of /api/objects/id in the branch 229.

**Review by helderbetiol — APPROVED** [review]
